from netscape_cookies import *

cookies = """
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.xl.co.id	TRUE	/	TRUE	1735737321	__cf_bm	L_ShUR.V9V2u.tHnhQceXkCJZMh6gH4CAmIC4ydBYfU-1735735521-1.0.1.1-F2lHu9pIkLr2Xnj65Qsa8ayS6067oQNSiDve3nOGUxYEhUCog3xa6p3IFO3frvbVHGU88gC5zLnNr86PRFQBDw
#HttpOnly_www.xlaxiata.co.id	FALSE	/	FALSE	1735907096	stickounet	1735734296.664.788.648751|165c449370a3ddbfb66e169bb6db9fc4
#HttpOnly_.xlaxiata.co.id	TRUE	/	TRUE	1735737320	__cf_bm	wFAi0O8oczaMFmlqGcWnCcXOwBZGlPTDXDI_wNAbm_4-1735735520-1.0.1.1-9M7fuJcLXHp0tqKwu.1XO.Ukt1M9DD6ZsGlaZl74rJfYP87LW44OIEs7HVE1aP2v20lSfAiuZEJL159fw.H3fA
.bing.com	TRUE	/	TRUE	1769431521	MUID	173CE01CBF5F678F06D1F57BBE0966BA
#HttpOnly_bing.com	FALSE	/	FALSE	1769431594	MUIDB	173CE01CBF5F678F06D1F57BBE0966BA
#HttpOnly_.bing.com	TRUE	/	FALSE	0	_EDGE_S	F=1&SID=35425DC7A68D68B3228F48A0A7DB6912
#HttpOnly_.bing.com	TRUE	/	FALSE	1769431521	_EDGE_V	1
"""

print(parse_from_string("#HttpOnly_.bing.com	TRUE	/	FALSE	1769431521	_EDGE_V	1"))
print(
    parse_from_string(
        "#HttpOnly_.xl.co.id	TRUE	/	TRUE	1735737321	__cf_bm	L_ShUR.V9V2u.tHnhQceXkCJZMh6gH4CAmIC4ydBYfU-1735735521-1.0.1."
    )
)
